from tatar_morph.types import (
    Tense,
    Case,
    Possessive,
    PunctuationType,
    PartOfSpeech,
    NonFiniteVerbForm,
    AnyType,
    PronounType,
    Gender,
    Number,
    Mood,
    Voice,
    NumeralType,
    ProperNounType,
    ModalParticleType,
    Person,
    Polarity,
    Usage,
    Transitivity,
    TechnicalTag,
    Formality,
    ComparisonDegree,
)

KNOWN_SYMBOLS_MAPPER: dict[str, AnyType] = {
    "gen": Case.GENITIVE,
    "fut2": Tense.DEFINITE_FUTURE,
    "ref": PronounType.REFLEXIVE,
    "mod_ind": ModalParticleType.INDEFINITE,
    "comp": ComparisonDegree.COMPARATIVE,
    "err_orth": TechnicalTag.ORTHOGRAPHIC_ERROR,
    "px2sg": Possessive.SECOND_SINGULAR,
    "evid": Mood.EVIDENTIAL,
    "ger_past": NonFiniteVerbForm.PAST_VERBAL_NOUN,
    "ind": PronounType.INDEFINITE,
    "abe": Case.ABESSIVE,
    "advl": Usage.ADVERBIAL,
    "adv": PartOfSpeech.ADVERB,
    "ger_fut3": NonFiniteVerbForm.PROSPECTIVE_VERBAL_NOUN,
    "gpr_past": NonFiniteVerbForm.PAST_VERBAL_ADJECTIVE,
    "lquot": PunctuationType.LEFT_QUOTE,
    "p3": Person.THIRD,
    "gna_until": NonFiniteVerbForm.UNTIL_CONVERB,
    "sg": Number.SINGULAR,
    "lline": PunctuationType.LOW_LINE,
    "f": Gender.FEMININE,
    "unk": ProperNounType.UNKNOWN,
    "org": ProperNounType.ORGANIZATION,
    "sent": PunctuationType.SENTENCE_MARKER,
    "cm": PunctuationType.COMMA,
    "p1": Person.FIRST,
    "ger": NonFiniteVerbForm.VERBAL_NOUN,
    "multipl": PunctuationType.MULTIPLICATION_SIGN,
    "adj": PartOfSpeech.ADJECTIVE,
    "guio": PunctuationType.HYPHEN,
    "prc_cond": NonFiniteVerbForm.CONDITIONAL_PARTICIPLE,
    "post": PartOfSpeech.POSTPOSITION,
    "px": Possessive.GENERAL,
    "mod_ass": ModalParticleType.ASSERTIVE,
    "prc_impf": NonFiniteVerbForm.IMPERFECT_PARTICIPLE,
    "ideo": PartOfSpeech.IDEOPHONE,
    "lpar": PunctuationType.LEFT_PARENTHESIS,
    "pat": ProperNounType.PATRONYMIC,
    "np": PartOfSpeech.PROPER_NOUN,
    "postadv": PartOfSpeech.POSTADVERB,
    "attr": Usage.ATTRIBUTIVE,
    "frm": Formality.FORMAL,
    "pres": Tense.PRESENT,
    "phrase": TechnicalTag.PHRASE,
    "v": PartOfSpeech.VERB,
    "registered": PunctuationType.REGISTERED_SIGN,
    "prc_vol": NonFiniteVerbForm.VOLITIONAL_PARTICIPLE,
    "copyright": PunctuationType.COPYRIGHT_SIGN,
    "ger_perf": NonFiniteVerbForm.PERFECT_VERBAL_NOUN,
    "gna_neg": NonFiniteVerbForm.NEGATIVE_CONVERB,
    "pound": PunctuationType.POUND_SIGN,
    "px2pl": Possessive.SECOND_PLURAL,
    "num": PartOfSpeech.NUMERAL,
    "px1pl": Possessive.FIRST_PLURAL,
    "det": PartOfSpeech.DETERMINER,
    "cop": PartOfSpeech.COPULA,
    "dollar": PunctuationType.DOLLAR_SIGN,
    "yen": PunctuationType.YEN_SIGN,
    "iv": Transitivity.INTRANSITIVE,
    "at": PunctuationType.COMMERCIAL_AT,
    "section": PunctuationType.SECTION_SIGN,
    "pass": Voice.PASSIVE,
    "gna_perf": NonFiniteVerbForm.PERFECT_CONVERB,
    "itg": PronounType.INTERROGATIVE,
    "apos": PunctuationType.APOSTROPHE,
    "dat": Case.DATIVE,
    "ger_ppot": NonFiniteVerbForm.ABILITY_VERBAL_NOUN,
    "coll": NumeralType.COLLECTIVE,
    "abbr": PartOfSpeech.ABBREVIATION,
    "ger_fut": NonFiniteVerbForm.INDEFINITE_FUTURE_VERBAL_NOUN,
    "gpr_ppot": NonFiniteVerbForm.ABILITY_VERBAL_ADJECTIVE,
    "dem": PronounType.DEMONSTRATIVE,
    "ifi": Tense.DEFINITE_PAST,
    "n": PartOfSpeech.NOUN,
    "rquot": PunctuationType.RIGHT_QUOTE,
    "coop": Voice.COOPERATIVE,
    "gpr_impf": NonFiniteVerbForm.IMPERFECT_VERBAL_ADJECTIVE,
    "cnjcoo": PartOfSpeech.COORDINATING_CONJUNCTION,
    "vaux": PartOfSpeech.AUXILIARY_VERB,
    "gpr_fut3": NonFiniteVerbForm.PROSPECTIVE_VERBAL_ADJECTIVE,
    "tv": Transitivity.TRANSITIVE,
    "gpr_pot": NonFiniteVerbForm.POTENTIAL_VERBAL_ADJECTIVE,
    "prc_perf": NonFiniteVerbForm.PERFECT_PARTICIPLE,
    "al": ProperNounType.OTHER,
    "subst": Usage.SUBSTANTIVE,
    "pl": Number.PLURAL,
    "quot": PunctuationType.QUOTE,
    "emph": ModalParticleType.EMPHATIC,
    "dist": NumeralType.DISTRIBUTIVE,
    "fut_plan": Tense.PLANNED_FUTURE,
    "gpr_fut2": NonFiniteVerbForm.DEFINITE_FUTURE_VERBAL_ADJECTIVE,
    "mf": Gender.MASCULINE_OR_FEMININE,
    "gna_after": NonFiniteVerbForm.AFTER_CONVERB,
    "euro": PunctuationType.EURO_SIGN,
    "ant": ProperNounType.ANTHROPONYM,
    "neg": Polarity.NEGATIVE,
    "top": ProperNounType.TOPONYM,
    "p2": Person.SECOND,
    "fut": Tense.INDEFINITE_FUTURE,
    "invquest": PunctuationType.INVERTED_QUESTION_MARK,
    "cnjadv": PartOfSpeech.ADVERBIAL_CONJUNCTION,
    "prn": PartOfSpeech.PRONOUN,
    "nom": Case.NOMINATIVE,
    "qst": ModalParticleType.QUESTION,
    "percent": PunctuationType.PERCENT_SIGN,
    "qnt": PronounType.QUANTIFIER,
    "abl": Case.ABLATIVE,
    "cog": ProperNounType.COGNOMEN,
    "px3sp": Possessive.THIRD_SINGULAR_OR_PLURAL,
    "acc": Case.ACCUSATIVE,
    "ger1": NonFiniteVerbForm.MAK_VERBAL_NOUN,
    "ord": NumeralType.ORDINAL,
    "px3pl": Possessive.THIRD_PLURAL,
    "imp": Mood.IMPERATIVE,
    "gpr_fut": NonFiniteVerbForm.INDEFINITE_FUTURE_VERBAL_ADJECTIVE,
    "pilcrow": PunctuationType.PILCROW,
    "sim": Case.SIMILATIVE,
    "ltr": PartOfSpeech.LETTER,
    "punct": PartOfSpeech.PUNCTUATION,
    "asterisk": PunctuationType.ASTERISK,
    "reas": Case.REASON,
    "past": Tense.PAST,
    "recip": PronounType.RECIPROCAL,
    "prc_fplan": NonFiniteVerbForm.PLANNED_FUTURE_PARTICIPLE,
    "caus": Voice.CAUSATIVE,
    "division": PunctuationType.DIVISION_SIGN,
    "tilde": PunctuationType.TILDE,
    "opt": Mood.OPTATIVE,
    "sp": Number.SINGULAR_OR_PLURAL,
    "vline": PunctuationType.VERTICAL_LINE,
    "inf": NonFiniteVerbForm.INFINITIVE,
    "cnjsub": PartOfSpeech.SUBORDINATING_CONJUNCTION,
    "ger_abs": NonFiniteVerbForm.ABSTRACT_VERBAL_NOUN,
    "m": Gender.MASCULINE,
    "pers": PronounType.PERSONAL,
    "ger_fut2": NonFiniteVerbForm.DEFINITE_FUTURE_VERBAL_NOUN,
    "gna_cond": NonFiniteVerbForm.CONDITIONAL_CONVERB,
    "ij": PartOfSpeech.INTERJECTION,
    "loc": Case.LOCATIVE,
    "rpar": PunctuationType.RIGHT_PARENTHESIS,
    "px1sg": Possessive.FIRST_SINGULAR,
    "equ": Case.EQUATIVE,
    "aor": Tense.AORIST,
}


def _build_feature_mapper() -> dict[tuple[type[AnyType], AnyType], str]:
    mapper: dict[tuple[type[AnyType], AnyType], str] = {}
    for symbol, feature in KNOWN_SYMBOLS_MAPPER.items():
        key = (type(feature), feature)
        if previous_symbol := mapper.get(key):
            raise RuntimeError(
                f"Feature {feature!r} has ambiguous HFST symbols: "
                f"{previous_symbol!r} and {symbol!r}"
            )
        mapper[key] = symbol
    return mapper


FEATURE_TO_KNOWN_SYMBOL = _build_feature_mapper()
